name: Test Sample apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  fetchSamples:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack Library
        run: |
            npm pack
            ls
            find . -type f -regex '.*/opentok-react-native-[0-9]\.[0-9]\.[0-9]\.tgz'
      - name: Checkout samples
        uses: actions/checkout@v2
        with:
          repository: opentok/opentok-react-native-samples
