name: Test Sample apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  fetchSamples:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack Library
        run: |
            npm pack
            ls
            shopt -s failglob
            for f in opentok-react-native-[[:digit:]].[[:digit:]].[[:digit:]].tgz; do new="$(printf '%s' "$f" | sed 's/react-native/new/')"; echo mv "$f" "$new"; done
      - name: Checkout samples
        uses: actions/checkout@v2
        with:
          repository: opentok/opentok-react-native-samples
